### ISSUE TITLE
Can't save files

### ISSUE THREAD

**Issue by efeefe** [flathub/com.getferdi.Ferdi#19]
Hi. I'm running Ferdi via Flatpak on Debian Bullseye. It's working perfect in general, except for the fact that I can not save files received from messengers (Whatsapp, Telegram). When I try it, it asks me where I want to save it, as expected. I click "save", but the file is not saved. I imagine it's related to permissions, but don't know where to allow it.

**Comment by lhw** [comment]
The flatpak is indeed limited to writing files only to ~/Downloads or the directory specified in your XDG variables for downloads[0]. The users home directory is set to read-only [1]. You can change the permissions via the built-in manager:
```
flatpak override com.getferdi.Ferdi --filesystem=home:rw
```
would for example allow read-write access to your home directory. You can also use the same line to allow access to other paths. Or simply to your whole filesystem like this:
```
flatpak override com.getferdi.Ferdi --filesystem=host
```

[0] https://github.com/flathub/com.getferdi.Ferdi/blob/master/com.getferdi.Ferdi.yaml#L18
[1] https://github.com/flathub/com.getferdi.Ferdi/blob/master/com.getferdi.Ferdi.yaml#L17

**Comment by efeefe** [comment]
It seems to have worked. Thanks a lot!
