### ISSUE TITLE
Ferdi starts in fullscreen

### ISSUE THREAD

**Issue by kir0ul** [flathub/com.getferdi.Ferdi#20]
Hi there,

Thanks for packaging Ferdi!

Not sure if this belongs to this repo or to Ferdi's repo, but it seems since the last version update, Ferdi starts in fullscreen and I can't find a way to exit the fullscreen mode.
Is anyone else having the same issue?

Flatpak info below:
```
$ flatpak info com.getferdi.Ferdi/x86_64/stable
Ref: app/com.getferdi.Ferdi/x86_64/stable
ID: com.getferdi.Ferdi
Arch: x86_64
Branch: stable
Origin: flathub
Collection ID: org.flathub.Stable
Date: 2021-09-20 12:01:00 +0000
Subject: Missed the metainfo update (a9ea8692)
Commit: 3f7e1afe1ef85b5c97d54bc2e25fb7ebf8de7284ac0cc2bcd28486e7a8a2848f
Parent: 3468ddb6e73034f135318da90b0b37043f2334ecce492761b3c2faeb260063bf
Location: /var/lib/flatpak/app/com.getferdi.Ferdi/x86_64/stable/3f7e1afe1ef85b5c97d54bc2e25fb7ebf8de7284ac0cc2bcd28486e7a8a2848f
Installed size: 323.0 MB
Runtime: org.freedesktop.Platform/x86_64/21.08
Sdk: org.freedesktop.Sdk/x86_64/21.08
```

**Comment by lhw** [comment]
I'm assuming you have tried <kbd>F11</kbd>?

I don't think I have experienced this with Ferdi. But it's very likely an issue with Ferdi itself and not the packaging. If you don't mind setting up your accounts again the easiest way to get to status quo is probably to purge the `~/.var/app/com.getferdi.Ferdi` directory. That would reset every user setting

**Comment by kir0ul** [comment]
Forgot to answer here but yes `F11` did the trick, sorry for the noise.

**Comment by GuillaumeSorel** [comment]
worked also for me
