### ISSUE TITLE
Upstream ferdi project is discontinued

### ISSUE THREAD

**Issue by CaramelHeaven** [flathub/com.getferdi.Ferdi#37]
https://getferdi.com/

Ferdi is not working right now and app is no longer available also

**Comment by lhw** [comment]
I have absolutely zero connection to the upstream project. Its just the packaging. I have no idea what happened to the upstream application. I won't update the application for the time being until it is clear what happened.

**Comment by lhw** [comment]
I was able to find some information on reddit: https://www.reddit.com/r/getferdi/comments/u2qck8/ferdi_is_officially_gone/

So I am guessing that's it for the ferdi project. https://meetfranz.com still exists as origin. So thats probably the next best solution.

**Comment by lhw** [comment]
Actually. I'll leave this open.

If you want to continue using ferdi for the moment just use the "continue without an account" option. But you might have to reconfigure all your services.

**Comment by LeSnake04** [comment]
Maybe add an end of life notice to the flathub.json

**Comment by lhw** [comment]
I'm currently evaluating how to continue. The Problem I foresee with creating a new version is that the old version tarball is no longer available at its original source link.
There is already a fork which is being worked on to make the transition as easy as possible. https://github.com/ferdium/ferdium-app but its not yet released. But they do have the previous version uploaded https://github.com/ferdium/ferdi/releases/tag/v5.8.1 but its not build from source

**Comment by ghost** [comment]
Whether or not you use the dev's behavior to judge the fate of this package is up to you, I'm just here to share what's been happening.

- [Screenshot of conversation with Ferdi dev from one of the former collaborators](https://github.com/pacstah/ferdium/issues/1#issuecomment-1098640566)
- [Ferdi dev reuploading an already privated video of a Youtuber that used to promote the app](https://twitter.com/BrodieOnLinux/status/1517324940974104581)

**Comment by lhw** [comment]
> Whether or not you use the dev's behavior to judge the fate of this package is up to you, I'm just here to share what's been happening.

Oh I am certainly aware of the situation. And I will not continue this version as I deem the behaviour of the original maintainer unacceptable. My message was more in the neighbourhood of how to create a new version of the flathub package with the included eol and rebase flags without the original source package being available.
I know they currently are available again but I can't tell for how long.

**Comment by ghost** [comment]
Hopefully Ferdium gets a proper release soon so this gets a replacement.

**Comment by lhw** [comment]
Closed via #38
