### ISSUE TITLE
Requires --own-name=org.kde.* to show tray icon

### ISSUE THREAD

**Issue by TiZ-HugLife** [flathub/com.getferdi.Ferdi#8]
Hi there. I noticed when I installed Ferdi that the tray icon didn't appear. I checked out permissions for both MS Teams and Zoom, which both have working tray icons. Teams has talk permissions on `org.kde.StatusNotifierWatcher', but Zoom has **own** permissions on 'org.kde.*'.

So when I did `flatpak override --own-name=org.kde.* com.getferdi.Ferdi`, the tray icon started to appear.

**Comment by lhw** [comment]
Will fix it today. I am somehow only getting the notifications for issues a week late.
